# Generated by Django 4.1.7 on 2024-09-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=40)),
                #('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
