# Generated by Django 5.1.1 on 2024-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='id',
            new_name='Id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
