# Generated by Django 4.1.7 on 2024-10-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_rename_id_agenda_id_alter_usuarios_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
